version: '3.3'

services:
  fpm:
    image: rendyananta/sample-todo-app:fpm
  nginx:
    image: rendyananta/sample-todo-app:nginx
    ports: 
      - "8080:80"
    volumes: 
      - ./opt/container/nginx/nginx.conf:/etc/nginx/nginx.conf
