apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-app
data:
  key: | 
  APP_NAME: "Todo App"
  APP_ENV: production
  APP_KEY: base64:SKhSTeTAIrlmnawXKrQZwFeUpeGvaZP8kxz7Hj9/OnU=
  APP_DEBUG: "false"
  APP_URL: http://localhost:8080

  LOG_CHANNEL: stderr
  LOG_LEVEL: debug

  DB_CONNECTION: mysql
  DB_HOST: mysql
  DB_PORT: "3306"
  DB_DATABASE: todo_app_db
  DB_FOREIGN_KEYS: "true"
  DB_USERNAME: "todo_app"

  BROADCAST_DRIVER: log
  CACHE_DRIVER: file
  FILESYSTEM_DRIVER: local
  QUEUE_CONNECTION: sync
  SESSION_DRIVER: redis
  SESSION_LIFETIME: "120"

  REDIS_HOST: "redis-master"
  REDIS_PORT: "6379"

  # MAIL_MAILER: smtp
  # MAIL_HOST: mailhog
  # MAIL_PORT: 1025
  # MAIL_USERNAME: null
  # MAIL_PASSWORD: null
  # MAIL_ENCRYPTION: null
  # MAIL_FROM_ADDRESS: null
  # MAIL_FROM_NAME: "${APP_NAME}"