apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-pvc
      containers:
      - name: mysql
        image: mariadb:10.6
        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
        ports:
        - containerPort: 3306
          name: mysql
        env:
        - name: MYSQL_RANDOM_ROOT_PASSWORD
          value: "true"
        - name: MYSQL_USER
          value: todo_app
        - name: MYSQL_PASSWORD
          valueFrom:
              secretKeyRef: 
                name: mysql-secret
                key: password
        - name: MYSQL_DATABASE
          value: todo_app_db
        volumeMounts:
          - mountPath: /var/lib/mysql
            name: mysql-data
              
