apiVersion: v1
kind: Secret
metadata:
  name: todo-app
  namespace: default
type: Opaque
data:
  APP_KEY: YmFzZTY0OlNLaFNUZVRBSXJsbW5hd1hLclFad0ZlVXBlR3ZhWlA4a3h6N0hqOS9PblU9Cg==
  DB_HOST: mysql.database.svc.cluster.local
  DB_PORT: "3306"
  DB_USERNAME: "todo_app"
  DB_PASSWORD: secretpassword
  DB_DATABASE: todo_app_db