apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todo-app-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/issuer: "todo-app-letsencrypt-prod"
spec:
  defaultBackend:
    service:
      name: todo-app
      port: 
        number: 80
  rules:
  - host: "todo-app.k8s.rendyananta.my.id"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: todo-app
            port:
              number: 80