apiVersion: v1
kind: Secret
metadata:
  name: todo-app
  namespace: default
type: Opaque
data:
  APP_KEY: YmFzZTY0OlNLaFNUZVRBSXJsbW5hd1hLclFad0ZlVXBlR3ZhWlA4a3h6N0hqOS9PblU9Cg==
  DB_PASSWORD: aW5zZWN1cmUtcm9vdC1wYXNzd29yZA==